### ISSUE TITLE
m72 rocket is breaking game sound

### ISSUE THREAD

**Issue by LusineWT** [Cypherado/Potato-Liberation#11]
EDIT: Snafu installed RHS incorrectly

- 14:48:21 Warning Message: No entry 'bin\config.bin/CfgWeapons.rhs_weap_m72a7'.
- 
- 14:48:21 Warning Message: No entry '.scope'.
- 
- 14:48:21 Warning Message: '/' is not a value
- 
- 14:48:21 Warning Message: Error: creating weapon rhs_weap_m72a7 with scope=private
- A
- 14:48:21 Warning Message: No entry '.displayName'.
- 
- 14:48:21 Warning Message: '/' is not a value
- 
- 14:48:21 Warning Message: No entry '.nameSound'.
- 
- 14:48:21 Warning Message: '/' is not a value
- 
- 14:48:21 Warning Message: No entry '.type'.
- 
- 14:48:21 Warning Message: '/' is not a value
- 
- 14:48:21 Warning Message: No entry '.picture'.
- 
- 14:48:21 Warning Message: '/' is not a value
- 
- 14:48:21 Warning Message: No entry '.Library'.
- 
- 14:48:21 Warning Message: No entry '.libTextDesc'.
- 
- 14:48:21 Warning Message: '/' is not a value
- 
- 14:48:21 Warning Message: No entry '.model'.
- 
- 14:48:21 Warning Message: '/' is not a value
- 
- 14:48:21 Warning Message: No entry '.simulation'.
- 
- 14:48:21 Warning Message: '/' is not a value
- 
- 14:48:21 Warning Message: No entry '.fireLightDuration'.
- 
- 14:48:21 Warning Message: '/' is not a value
- 
- 14:48:21 Warning Message: No entry '.fireLightIntensity'.
- 
- 14:48:21 Warning Message: '/' is not a value
- 
- 14:48:21 Warning Message: No entry '.fireLightDiffuse'.
- 
- 14:48:21 Warning Message: Size: '/' not an array
- 
- 14:48:21 Warning Message: Size: '/' not an array
- 
- 14:48:21 Warning Message: No entry '.fireLightAmbient'.
- 
- 14:48:21 Warning Message: Size: '/' not an array
- 
- 14:48:21 Warning Message: Size: '/' not an array
- 
- 14:48:21 Warning Message: No entry '.weaponLockDelay'.
- 
- 14:48:21 Warning Message: '/' is not a value
- 
- 14:48:21 Warning Message: No entry '.weaponLockSystem'.
- 
- 14:48:21 Warning Message: '/' is not a value
- 
- 14:48:21 Warning Message: No entry '.cmImmunity'.
- 
- 14:48:21 Warning Message: '/' is not a value
- 
- 14:48:21 Warning Message: No entry '.weight'.
- 
- 14:48:21 Warning Message: '/' is not a value
- 
- 14:48:21 Warning Message: No entry '.lockingTargetSound'.
- 
- 14:48:21 Warning Message: Size: '/' not an array
- 
- 14:48:21 Warning Message: No entry '.lockedTargetSound'.
- 
- 14:48:21 Warning Message: Size: '/' not an array
- 
- 14:48:21 Warning Message: No entry '.detectRange'.
- 
- 14:48:21 Warning Message: '/' is not a value
- 
- 14:48:21 Warning Message: No entry '.muzzles'.
- 
- 14:48:21 Warning Message: Size: '/' not an array

**Comment by Cypherado** [comment]
Just checked with sooty and snafu, it's confirmed to be fixed. Closing the ticket.
