### ISSUE TITLE
Fix Enemy Vehicles blowing up

### ISSUE THREAD

**Issue by LusineWT** [Cypherado/Potato-Liberation#22]
C:\Users\****\Documents\Arma 3\missions\Liberation_PotatoEdit2V1_3.Altis\scripts\server\ai\csat_vechile_abadon_vehicle.sqf

Remove line 13? 	
_veh setdamage 1;

**Comment by Cypherado** [comment]
Lowered chance for it to explode instead of outright removing it. Can't have all the ammo.
