### ISSUE TITLE
Sector Ownership Values

### ISSUE THREAD

**Issue by LusineWT** [Cypherado/Potato-Liberation#23]
C:\Users\xxx\Documents\Arma 3\missions\xxx\scripts\shared\functionsF_sectorOwnership.sqf

Change both lines

Line 4:
 _cap_thresold_count = 10;  // Caps when Enemy AI count drops below this value

Line 19: 
if ( _countblufor_ownership > 0 &&  _countopfor_ownership < _cap_thresold_count ) then { _sectorside = GRLIB_side_friendly; };

**Comment by Cypherado** [comment]
Changed.
