### ISSUE TITLE
TODO: Increase vehicle costs

### ISSUE THREAD

**Issue by LusineWT** [Cypherado/Potato-Liberation#25]
MH-9 Armed variants need to cost at least 150 ammo
AH-64 & AH-1Z needs to cost at least 350 ammo
UH-1Y Armed needs to cost at least 150 ammo
AT-6 Texan needs to cost at least 400 ammo
M163 Vulcan needs to cost at least 100 ammo

**Comment by Cypherado** [comment]
Done. Changes are in my testing branch.
