### ISSUE TITLE
TODO: Item Blacklist

### ISSUE THREAD

**Issue by LusineWT** [Cypherado/Potato-Liberation#26]
Various stun grenades need blacklisted
VR suit blacklist?

EDIT: 
```
rhs_ammo_fakel
rhs_ammo_fakels
rhs_ammo_zarya2
rhs_ammo_plamyam
rhs_ammo_m7a3_cs
rhs_ammo_mk3a2
rhs_ammo_m84
```

**Comment by Cypherado** [comment]
Yeah. Certain stuff needs out. But the arsenal blacklist is actually a whitelist so we need to add everything else instead.

**Comment by LusineWT** [comment]
Create a new blacklist script? Adding everything for the Barbie's will be impossible.

**Comment by LusineWT** [comment]
Added listed grenades to blacklist. Found GL stun grenades and also added them to blacklist.
Closed Ticket.
