### ISSUE TITLE
TODO: New objects to be added

### ISSUE THREAD

**Issue by LusineWT** [Cypherado/Potato-Liberation#31]
Needed:
`Land_TentHangar__V1_F`

Optional:
`Land_Mil_WallBig_4m_F`

Immersion Ruining Gag & Game Breaking: (Replace FOB)
`Land_Supermarket_01_F`

**Comment by Cypherado** [comment]
`Land_TentHangar__V1_F` and `Land_Mil_WallBig_4m_F` will be added for 1.3.3

I'll probably make it a 10% chance for a FOB to actually be a supermarket if it's trivial to implement.

**Comment by LusineWT** [comment]
Added hangar and walls. The FOB doesnt seem worth the time it would take to test.
 Ticket Closed.
