### ISSUE TITLE
TODO: Remove CUP Units and Vehicles

### ISSUE THREAD

**Issue by LusineWT** [Cypherado/Potato-Liberation#45]
Help trim down the mod list and hopefully help with any crashing issues.

**Comment by Cypherado** [comment]
Already done. [https://github.com/Cypherado/Potato-Liberation/tree/vanilla](https://github.com/Cypherado/Potato-Liberation/tree/vanilla). 
Mission is loaded on the server. Only thing I didn't do is change the required mods in the commandline
