### ISSUE TITLE
Earplugs known issues

### ISSUE THREAD

**Issue by Cypherado** [Cypherado/Potato-Liberation#5]
* Earplugs need to be toggled on again after leaving a vehicle (pretty sure it's the script for the in-vehicle sound interfering)

* Earplugs need to be toggled off, then on again after being revived.

**Comment by LusineWT** [comment]
game breaking bug, will not return to play ever again.

**Comment by Cypherado** [comment]
Earplugs are now respecting the user's in-vehicle volume.

Revive issue still being looked at.

**Comment by LusineWT** [comment]
REOPENED! BAM!
Revive issue not resolved.

**Comment by Cypherado** [comment]
Yep, been working on a fix. I think I have something just need to test it with another player and not an AI.

**Comment by Cypherado** [comment]
Tested the fix with Quirky. It works. Earplugs state is correctly remembered upon revive.
[https://github.com/Cypherado/Potato-Liberation/commit/9c658ea738e82b0edf5c5b8e1f716426fbeb7f0d](https://github.com/Cypherado/Potato-Liberation/commit/9c658ea738e82b0edf5c5b8e1f716426fbeb7f0d)
